# Generated by Django 2.1.5 on 2019-01-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20190130_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='almacen',
            field=models.IntegerField(default=0),
        ),
    ]
