# Generated by Django 2.1.5 on 2019-01-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20190130_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='almacen',
            field=models.PositiveIntegerField(),
        ),
    ]
